apiVersion: v1beta1
kind: ReplicationController
metadata:
  name: nginx-demo
spec:
  replicas: 2
  selector:
    app: nginx-leatest
  template:
    metadata: 
      labels:
        app: nginx-leatest
  spec:
    containers:
      - name: nginx-leatest
        image: nginx:latest
        ports:
        - containerPort: 8080
